import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';
import { EHILogoPDF } from '../EHILogoPDF';

export interface WeightManifestPDFEntry {
  airline: string;
  flight_number: string;
  route: string;
  total_pieces: number;
  total_kg: number;
  verified: boolean;
  verified_by: string | null;
  verified_at: string | null;
}

export interface WeightManifestPDFData {
  hubName: string;
  date: string;
  generatedBy: string;
  entries: WeightManifestPDFEntry[];
  totalPieces: number;
  totalKg: number;
  verifiedCount: number;
}

const styles = StyleSheet.create({
  page: { padding: 30, fontFamily: 'Helvetica', fontSize: 10 },
  header: { marginBottom: 20 },
  title: { fontSize: 12, color: '#6b7280', textTransform: 'uppercase', marginBottom: 20 },

  table: { display: 'flex', width: 'auto', borderStyle: 'solid', borderWidth: 1, borderRightWidth: 0, borderBottomWidth: 0, borderColor: '#e5e7eb', marginTop: 10 },
  tableRow: { flexDirection: 'row' },
  tableColHeader: { flex: 1, borderStyle: 'solid', borderWidth: 1, borderLeftWidth: 0, borderTopWidth: 0, borderColor: '#e5e7eb', backgroundColor: '#f9fafb', padding: 5 },
  tableColHeaderWide: { flex: 2, borderStyle: 'solid', borderWidth: 1, borderLeftWidth: 0, borderTopWidth: 0, borderColor: '#e5e7eb', backgroundColor: '#f9fafb', padding: 5 },
  tableColHeaderNarrow: { width: '10%', borderStyle: 'solid', borderWidth: 1, borderLeftWidth: 0, borderTopWidth: 0, borderColor: '#e5e7eb', backgroundColor: '#f9fafb', padding: 5 },
  tableCol: { flex: 1, borderStyle: 'solid', borderWidth: 1, borderLeftWidth: 0, borderTopWidth: 0, borderColor: '#e5e7eb', padding: 5 },
  tableColWide: { flex: 2, borderStyle: 'solid', borderWidth: 1, borderLeftWidth: 0, borderTopWidth: 0, borderColor: '#e5e7eb', padding: 5 },
  tableColNarrow: { width: '10%', borderStyle: 'solid', borderWidth: 1, borderLeftWidth: 0, borderTopWidth: 0, borderColor: '#e5e7eb', padding: 5 },
  tableCellHeader: { fontSize: 8, fontWeight: 'bold' },
  tableCell: { fontSize: 8 },

  summaryBox: { marginTop: 20, padding: 15, backgroundColor: '#f9fafb', borderRadius: 4, borderWidth: 1, borderColor: '#e5e7eb', flexDirection: 'row', justifyContent: 'space-between' },
  summaryLabel: { fontSize: 9, color: '#4b5563' },
  summaryValue: { fontSize: 10, fontWeight: 'bold' },

  footer: { marginTop: 30, fontSize: 8, color: '#9ca3af', textAlign: 'center' },
});

const WeightManifestPDFDoc = ({ data }: { data: WeightManifestPDFData }) => (
  <Document>
    <Page size="A4" orientation="landscape" style={styles.page}>
      <View style={styles.header}>
        <View style={{ alignItems: 'center', marginBottom: 15 }}>
          <EHILogoPDF width={120} />
        </View>
        <Text style={styles.title}>DAILY WEIGHT MANIFEST</Text>
        <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginTop: 10 }}>
          <Text style={{ fontSize: 9 }}>Date: {data.date}</Text>
          <Text style={{ fontSize: 9 }}>Hub: {data.hubName}</Text>
          <Text style={{ fontSize: 9 }}>Generated by: {data.generatedBy}</Text>
        </View>
      </View>

      <View style={styles.table}>
        <View style={styles.tableRow}>
          <View style={styles.tableColHeader}><Text style={styles.tableCellHeader}>AIRLINE</Text></View>
          <View style={styles.tableColHeaderNarrow}><Text style={styles.tableCellHeader}>FLIGHT</Text></View>
          <View style={styles.tableColHeaderWide}><Text style={styles.tableCellHeader}>ROUTE</Text></View>
          <View style={styles.tableColHeaderNarrow}><Text style={styles.tableCellHeader}>PIECES</Text></View>
          <View style={styles.tableColHeaderNarrow}><Text style={styles.tableCellHeader}>KG</Text></View>
          <View style={styles.tableColHeader}><Text style={styles.tableCellHeader}>VERIFIED BY</Text></View>
          <View style={styles.tableColHeader}><Text style={styles.tableCellHeader}>VERIFIED AT</Text></View>
        </View>
        {data.entries.map((e, i) => (
          <View style={styles.tableRow} key={i}>
            <View style={styles.tableCol}><Text style={styles.tableCell}>{e.airline}</Text></View>
            <View style={styles.tableColNarrow}><Text style={styles.tableCell}>{e.flight_number}</Text></View>
            <View style={styles.tableColWide}><Text style={styles.tableCell}>{e.route}</Text></View>
            <View style={styles.tableColNarrow}><Text style={styles.tableCell}>{e.total_pieces}</Text></View>
            <View style={styles.tableColNarrow}><Text style={styles.tableCell}>{e.total_kg.toFixed(1)}</Text></View>
            <View style={styles.tableCol}><Text style={styles.tableCell}>{e.verified_by || '-'}</Text></View>
            <View style={styles.tableCol}><Text style={styles.tableCell}>{e.verified_at ? new Date(e.verified_at).toLocaleString('en-GB') : '-'}</Text></View>
          </View>
        ))}
      </View>

      <View style={styles.summaryBox}>
        <View><Text style={styles.summaryLabel}>Total Dispatches</Text><Text style={styles.summaryValue}>{data.entries.length}</Text></View>
        <View><Text style={styles.summaryLabel}>Total Pieces</Text><Text style={styles.summaryValue}>{data.totalPieces}</Text></View>
        <View><Text style={styles.summaryLabel}>Total KG</Text><Text style={styles.summaryValue}>{data.totalKg.toFixed(1)}</Text></View>
        <View><Text style={styles.summaryLabel}>Verified</Text><Text style={styles.summaryValue}>{data.verifiedCount} / {data.entries.length}</Text></View>
      </View>

      <Text style={styles.footer}>Generated by EHI Logistics Platform</Text>
    </Page>
  </Document>
);

export const downloadWeightManifestPDF = async (data: WeightManifestPDFData) => {
  const blob = await pdf(<WeightManifestPDFDoc data={data} />).toBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `WeightManifest_${data.date}.pdf`;
  a.click();
  URL.revokeObjectURL(url);
};
